#!/bin/bash

BASE_DIR=$1
FROM_NAME=$2
FILENAME=$(basename "$3")
EXTENSION="${FILENAME##*.}"
FILENAME="${FILENAME%.*}"
EXTRA_INFO=$4
TARGET_NAME="$FILENAME""$EXTRA_INFO"."$EXTENSION"
TARGET_DIR="$BASE_DIR/$FILENAME"

mkdir -p "$TARGET_DIR"
ln "$FROM_NAME" "$TARGET_DIR/$TARGET_NAME"
chmod -R g+rw,u+rw,o+rx "$TARGET_DIR"
chown -R nobody:media "$TARGET_DIR"
