#!/bin/bash

BASE_DIR=$1
FROM_NAME=$2
TARGET_NAME=$3
TARGET_FNAME=${TARGET_NAME%.*}
TARGET_DIR="$BASE_DIR/$TARGET_FNAME"

mkdir -p "$TARGET_DIR"
mv "$FROM_NAME" "$TARGET_DIR/$TARGET_NAME"
chown -R nobody:nogroup "$TARGET_DIR"
ln -s "$TARGET_DIR/$TARGET_NAME" "$FROM_NAME"
